apiVersion: apps.nebula-graph.io/v1alpha1
kind: NebulaCluster
metadata:
  name: pneuma-memory
  namespace: default
spec:
  # The Graph Service (Query Engine)
  graphd:
    replicas: 2
    image: vesoft/nebula-graphd:v3.6.0
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
  # The Meta Service (Topology)
  metad:
    replicas: 3
    image: vesoft/nebula-metad:v3.6.0
    dataVolumeClaim:
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard
  # The Storage Service (Data - The Billions of Nodes)
  storaged:
    replicas: 3
    image: vesoft/nebula-storaged:v3.6.0
    dataVolumeClaim:
      resources:
        requests:
          storage: 100Gi # Scale this for production
      storageClassName: standard
    enableAutoBalance: true