apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 6333
      targetPort: 6333
    - name: grpc
      port: 6334
      targetPort: 6334
  selector:
    app: qdrant
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pneuma-qdrant
  namespace: default
spec:
  serviceName: "qdrant-service"
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:v1.12.0
        ports:
        - containerPort: 6333
        - containerPort: 6334
        resources:
          requests:
            cpu: "200m"
            memory: "500Mi"
        volumeMounts:
        - mountPath: /qdrant/storage
          name: qdrant-storage
  volumeClaimTemplates:
  - metadata:
      name: qdrant-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi